Friendships Milestone 3
karvel-code/ror-social-scaffold pull request #3
Opened 2021-07-08 09:07 UTC by karvel-code

In this section I have:
- Updated the Rails routes.
- Add a delete feature button for friendships.

2021-07-08 13:49 UTC, Elbie-em requested changes
## STATUS: CHANGES REQUIRED 🟡  ♻️ 

Hi @karvel-code, this is a very impressive approach you have taken in creating the inverse friendship functionality. However, the milestone initial requirement has not been met. Please check my comments below ⬇️  and make the necessary changes in order for this milestone to be approved.

### [OPTIONAL]

- [ ] The user's view is showing all users including the current user, you could simply create a query that shows all users except the current user in your controller.
- [ ] The Pending  link can be an action to cancel the request.
- [ ] If the users are friends, the Friends link can be an action to cancel the friendship.

*All the best and good luck* 💪 

> Elbie Moonga (Part-time TSE)

> Github (@Elbie-em)
> Slack (Elbie Moonga)
> Twitter ([@ElbieEm](https://twitter.com/ElbieEm))
> LinkedIn([Elbie Moonga](https://www.linkedin.com/in/elbiemoonga/))

2021-07-08 13:49 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
>      @friendship.update_attribute(:confirmed, true)
- [ ] when friendship is confirmed, an additional row with reversed user-friend pair is created, which means your table should have a reversed row created upon confirmation. e.g
  id:1  user_id: 1 friend_id: 2 ,confirmed: true
  id:2  user_id 2 friend_id 1, confirmed: true
The friendship IDs do not need to be contiguous as users may accept requests at a later time.
The goal is to allow users to access their friends by used the friend_id.

2021-07-08 13:49 UTC, Elbie-em commented on app/controllers/friendships_controller.rb
> +
- [ ] Kindly remove commented code, this will make your controller look more clean and professional.

2021-07-12 10:56 UTC, mke2111 approved these changes
# 😄 🥇  STATUS: APPROVED  🥇 👏🏽 

## Hey Happy Coder, 👋🏽 
Congratulations, 🥂 . You got minimum requirements for approval. 👍🏽 

### **_Well Done_** 💯 

    1. The app runs just fine. 👍🏽 


### **_Room for Improvement_** 🤪 

    1. The

### You may now merge to the develop branch and remember to submit a project completion form.
### I wish you the very best in your upcoming projects.

**Cheers 🍹 and Happy coding 💻** 

<hr>

### Best regards
Slack 🆘  Roy Mukuye
Twitter 🐦  [Roy Mukuye](https://twitter.com/Roymkenya)
LinkedIn 🔗  [Roy Mukuye](https://www.linkedin.com/in/roy-mukuye/)

2021-07-12 10:57 UTC, merged